from pptx import Presentation
from pptx.util import Inches, Pt

class PPTXGenerator:
    def __init__(self):
        self.prs = Presentation()

    def create_presentation(self, data, output_file="presentation.pptx"):
        # Title Slide
        title_slide_layout = self.prs.slide_layouts[0]
        slide = self.prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        
        # Try to get title from data, fallback if structure varies
        if "presentation_title" in data:
             title.text = self._clean_text(data["presentation_title"])
        elif "slides" in data and len(data["slides"]) > 0:
             title.text = self._clean_text(data["slides"][0].get("title", "Presentation"))
        else:
             title.text = "Presentation"

        subtitle.text = "Generated by Agentic AI"

        # Content Slides
        slides_data = data.get("refined_slides", data.get("slides", []))
        
        for slide_data in slides_data:
            layout_type = slide_data.get("layout_type", "bullets")
            
            if layout_type == "title":
                slide_layout = self.prs.slide_layouts[0]
                slide = self.prs.slides.add_slide(slide_layout)
                slide.shapes.title.text = self._clean_text(slide_data.get("title", ""))
                continue

            # Bullet layout
            slide_layout = self.prs.slide_layouts[1]
            slide = self.prs.slides.add_slide(slide_layout)
            
            # Title
            title_shape = slide.shapes.title
            title_shape.text = self._clean_text(slide_data.get("title", ""))
            
            # Safe title layout
            title_shape.left = Inches(0.5)
            title_shape.top = Inches(0.5)
            title_shape.width = Inches(9.0)
            title_shape.height = Inches(1.0)
            if title_shape.text_frame:
                for paragraph in title_shape.text_frame.paragraphs:
                    paragraph.font.size = Pt(32)
                    paragraph.font.bold = True
            
            # Content
            body_shape = slide.placeholders[1]
            body_shape.top = Inches(1.8) # Push content down
            body_shape.width = Inches(8.5) # Ensure full width by default
            body_shape.height = Inches(5.0)
            
            tf = body_shape.text_frame
            tf.word_wrap = True
            
            # Handle new 'bullet_points' key, fallback to 'content'
            content_points = slide_data.get("bullet_points", slide_data.get("content", []))
            if isinstance(content_points, str):
                content_points = [content_points]
                
            for point in content_points:
                p = tf.add_paragraph()
                p.text = self._clean_text(point)
                p.level = 0
                p.font.size = Pt(18)

            # Add Image if present
            if "image_path" in slide_data and slide_data["image_path"]:
                try:
                    # Resize text frame to make room for image
                    body_shape.width = Inches(5.0)
                    
                    # Add image to the right side
                    left = Inches(5.5)
                    top = Inches(1.8) # Align with content top
                    height = Inches(4.5)
                    slide.shapes.add_picture(slide_data["image_path"], left, top, height=height)
                except Exception as e:
                    print(f"Error adding image to slide: {e}")

            # Add speaker notes
            if "speaker_notes" in slide_data:
                notes_slide = slide.notes_slide
                text_frame = notes_slide.notes_text_frame
                text_frame.text = self._clean_text(slide_data["speaker_notes"])

        self.prs.save(output_file)
        print(f"Presentation saved to {output_file}")

    def _clean_text(self, text):
        if not text:
            return ""
        # Remove markdown bold/italic markers
        text = text.replace("**", "").replace("*", "").replace("`", "")
        return text
